language: scala
scala:
  - 2.11.5
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d5ea16a2f66f60a590b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

