language: scala
scala:
- 2.11.6
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && $(cat
  version.sbt) =~ "-SNAPSHOT" ]]; then sbt ++$TRAVIS_SCALA_VERSION coverage validate
  coverageReport && bash <(curl -s https://codecov.io/bash) && sbt clean validate
  publish gitSnapshots publish ; else sbt ++$TRAVIS_SCALA_VERSION coverage validate
  coverageReport && bash <(curl -s https://codecov.io/bash) && sbt clean validate
  publishLocal ; fi
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2d5ea16a2f66f60a590b
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
  - secure: pOukhzLWqqUx+5kBKwEXglml1S6VMnbIH7KcH07DZah21FgPnLmPHRQkvhPwWeBrPZw1spF5/0fEdGgeYhGuCo4GSqYikGUA+XOnmo9TNJDFqr1MFaNuNL0aVeHlhuJRoaX4Ql+jrgv0sdEpA8n/JVsQ+4ycTBIstnPcC6ax8Tk=
  - secure: bzZ7rAsyk/Z7IE8Uui9SlvdZ1rew3a876cN1K9vj07jHunD6kKXKwaJyYP0nrq8GC2EYw/GnF1ZkXmROYgeLJ1rpJgZD6TLqZyzIdsdZJClHbMfVRGfM3lwwvHiOVt1Kln9XQivUeSZLk5Z7bbNk0lt9yZTDnJwwLRBKFim98/Q=
