language: scala
git:
  depth: 9999
scala:
- 2.10.5
- 2.11.7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" &&
        "$TRAVIS_BRANCH" == "master" &&
        $(cat version.sbt) =~ "-SNAPSHOT"
  ]]; then
    sbt ++$TRAVIS_SCALA_VERSION coverage validateJVM coverageReport && bash <(curl -s https://codecov.io/bash) && sbt ++$TRAVIS_SCALA_VERSION clean macrosJS/compile coreJS/compile lawsJS/compile && sbt ++$TRAVIS_SCALA_VERSION testsJS/test && sbt ++$TRAVIS_SCALA_VERSION freeJS/test && sbt ++$TRAVIS_SCALA_VERSION stateJS/test && sbt ++$TRAVIS_SCALA_VERSION validateJVM publish gitSnapshots publish ;
  else
    sbt ++$TRAVIS_SCALA_VERSION coverage validateJVM coverageReport && bash <(curl -s https://codecov.io/bash) && sbt ++$TRAVIS_SCALA_VERSION clean macrosJS/compile coreJS/compile lawsJS/compile && sbt ++$TRAVIS_SCALA_VERSION testsJS/test && sbt ++$TRAVIS_SCALA_VERSION freeJS/test && sbt ++$TRAVIS_SCALA_VERSION stateJS/test && sbt ++$TRAVIS_SCALA_VERSION validateJVM publishLocal ;
  fi
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2d5ea16a2f66f60a590b
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
  - secure: J5G2482077TjxHmqMfEvkfFIq1ZFQ+G9ETs3GeFcIvlGyudmAZTEHmslDandbUjEypw4fTeZsnxdUxMs+6OjbkGakuUyrOEaOAVQpnmEKQCHfSDLlXdCKB1ftBcybKeLElN2AsUp/irXTy32VkXkFyOFmB3lzBDnnsPoog9Rcms=
  - secure: iAU22WspzZr1sJHgZBJ6zE0HWV3PaNi11dETlR4ZERxD/aUdEbjWhnTKGeeKOSD+cFio4UFJ9ruZobvxDWELgekSjjCesN2pXk6fTgYTEq/FdNaFZbCuKbs2XW3V8f7pXkh/IoXjLvdDzxzlLcqo5TkaeubBJbf4p77yfep/7pc=
